In [40]:
import numpy as np 


def compute_gradient_n_features(X,y,w,b):
    m,n = X.shape
    
    dj_dw = np.zeros(n)
    dj_db = 0
    
    for i in range(m):
        f_wb_i = np.dot(w , X[i]) + b 
        err = f_wb_i - y[i]
        
        dj_dw += err * X[i]
        # for j in range(n):
        #     dj_dw_j = err *  X[i,j]
        #     dj_dw[j] += dj_dw_j
        dj_db += err
        
    dj_dw /= m
    dj_db /= m
       
    return (dj_dw,dj_db)

def compute_gradient_n_features_vec(X,y,w,b):
    m,n = X.shape
    print("here 1")
    dj_dw = None
    dj_db = None
    print("here 2")

    f_wb = np.dot(X,w) + b
    err = f_wb - y
    print("here 3")

    dj_dw = np.sum( X * err.reshape(-1,1) , axis=0 )
    print("here 4")

    dj_db = np.sum(err)
    dj_dw = dj_dw.astype(float)
   
    dj_dw /= m
    dj_db /= m
                
    return (dj_dw,dj_db)
    # 
    

In [10]:
arr = np.arange(20).reshape(-1,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [41]:
gd = compute_gradient_n_features(arr,arr[:,2],arr[0],10)
gd_vec = compute_gradient_n_features_vec(arr,arr[:,2],arr[0],10)

gd_vec


here 1
here 2
here 3
here 4


(array([1072.5, 1178. , 1283.5, 1389. , 1494.5]), np.float64(105.5))